MONGODB_HOST: mongodb-{{ env }}.learndevops.fun # mongodb-dev.daws86s.fun
REDIS_HOST: redis-{{ env }}.learndevops.fun
CATALOGUE_HOST: catalogue.backend-alb-{{ env }}.learndevops.fun
CART_HOST: cart.backend-alb-{{ env }}.learndevops.fun
USER_HOST: user.backend-alb-{{ env }}.learndevops.fun
RABBITMQ_HOST: rabbitmq-{{ env }}.learndevops.fun
MYSQL_HOST: mysql-{{ env }}.learndevops.fun
SHIPPING_HOST: shipping.backend-alb-{{ env }}.learndevops.fun
PAYMENT_HOST: payment.backend-alb-{{ env }}.learndevops.fun